version: "3.7"

services:
    redis:
        image: redis:6
        volumes:
            - redis-data:/data

    api:
        init: true
        build:
            context: .
            dockerfile: docker/api/Dockerfile
        ports:
            - 3000:10080
        environment:
            PORT: 10080
            REDIS_URL: "//redis:6379"
        depends_on:
            - redis

    worker:
        init: true
        build:
            context: .
            dockerfile: docker/worker/Dockerfile
        environment:
            DEBUG: timers:*
            REDIS_URL: "//redis:6379"
        depends_on:
            - redis

volumes:
    redis-data:
